- name: Make project dir
  command: mkdir -p {{app_dir}}/{{app_name}}

- name: Make sockets dir
  command: mkdir -p {{app_path}}/shared/tmp/sockets

- name: Make config dir
  command: mkdir -p {{app_path}}/shared/config

- name: Copy database.yml
  template: src=database.yml.j2 dest={{app_path}}/shared/config/database.yml

- name: Setup ownership for project dir
  command: chown -R {{deploy_user}} {{app_dir}}/{{app_name}}

- name: Setup rights for project dir
  command: chmod -R g+w {{app_dir}}/{{app_name}}

- include: imagemagick.yml tags=setup