- name: ensure packages are installed
  action: apt name={{item}}
  with_items:
    - libpq-dev
    - python-psycopg2

- name: Install python-pycurl
  apt: pkg=python-pycurl state=latest
  
- name: Add PostgreSQL repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
  
- name: Add PostgreSQL repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

- name: Install PostgreSQL
  apt: pkg=postgresql-9.3 state=latest update_cache=true
  